/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Registration"
 * 	found in "Registration.asn1"
 * 	`asn1c -D src -no-gen-OER -no-gen-example`
 */

#ifndef	_Registration_H_
#define	_Registration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Registration */
typedef struct Registration {
	UTF8String_t	 firstName;
	UTF8String_t	 lastName;
	UTF8String_t	 email;
	UTF8String_t	 phone;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Registration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Registration;

#ifdef __cplusplus
}
#endif

#endif	/* _Registration_H_ */
#include <asn_internal.h>
