/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Registration"
 * 	found in "Registration.asn1"
 * 	`asn1c -D src -no-gen-OER -no-gen-example`
 */

#include "Registration.h"

static asn_TYPE_member_t asn_MBR_Registration_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Registration, firstName),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"firstName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Registration, lastName),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lastName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Registration, email),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"email"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Registration, phone),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"phone"
		},
};
static const ber_tlv_tag_t asn_DEF_Registration_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Registration_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 0, 0, 3 }, /* firstName */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 1, -1, 2 }, /* lastName */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 2, -2, 1 }, /* email */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 3, -3, 0 } /* phone */
};
static asn_SEQUENCE_specifics_t asn_SPC_Registration_specs_1 = {
	sizeof(struct Registration),
	offsetof(struct Registration, _asn_ctx),
	asn_MAP_Registration_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Registration = {
	"Registration",
	"Registration",
	&asn_OP_SEQUENCE,
	asn_DEF_Registration_tags_1,
	sizeof(asn_DEF_Registration_tags_1)
		/sizeof(asn_DEF_Registration_tags_1[0]), /* 1 */
	asn_DEF_Registration_tags_1,	/* Same as above */
	sizeof(asn_DEF_Registration_tags_1)
		/sizeof(asn_DEF_Registration_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Registration_1,
	4,	/* Elements count */
	&asn_SPC_Registration_specs_1	/* Additional specs */
};

